---
title: "Specific causes six states"
author: "Andrew Ba Tran"
date: "6/04/2020"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

# Between March 1 and May 30

Anything after is too affected by reporting lag.

```{r setup, warning=F, message=F}
library(tidyverse)
library(knitr)
library(janitor)
library(lubridate)

# run 01_all_causes.R and 02_causes_modeling.R to generate the spreadsheet below

todays_date <- as.character(Sys.Date())
file_path <-  paste0("cause.summary.state.df_", todays_date, ".csv")
causes <- read_csv(file_path)


type_list <- unique(causes$type)

states_list <- c("NY", "NYC", "IL", "MA", "NJ", "MI")

weeks_in <- 1:23
weeks_march <- 10:23
```


## diseases_of_heart_i00_i09

```{r diseases_of_heart_i00_i09, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="diseases_of_heart_i00_i09")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
 # filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess diseases_of_heart_i00_i09") +
  theme_minimal()

kable(mar_summary)
mar_summary$type <- "diseases of heart"
write_csv(mar_summary, "diseases_of_heart.csv")
```

## alzheimer_disease_g30

```{r alzheimer_disease_g30, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="alzheimer_disease_g30")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess alzheimer_disease_g30") +
  theme_minimal()

kable(mar_summary)


mar_summary$type <- "alzheimer disease"
write_csv(mar_summary, "alzheimer_disease.csv")
```


## cerebrovascular_diseases

```{r cerebrovascular_diseases, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="cerebrovascular_diseases")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess cerebrovascular_diseases") +
  theme_minimal()

kable(mar_summary)
```


## chronic_lower_respiratory

```{r chronic_lower_respiratory, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="chronic_lower_respiratory")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess chronic_lower_respiratory") +
  theme_minimal()

kable(mar_summary)
```


## diabetes_mellitus_e10_e14

```{r diabetes_mellitus_e10_e14, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="diabetes_mellitus_e10_e14")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess diabetes_mellitus_e10_e14") +
  theme_minimal()

kable(mar_summary)
```


## influenza_and_pneumonia_j10

```{r influenza_and_pneumonia_j10, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="influenza_and_pneumonia_j10")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess influenza_and_pneumonia_j10") +
  theme_minimal()

kable(mar_summary)
```



## malignant_neoplasms_c00_c97

```{r malignant_neoplasms_c00_c97, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="malignant_neoplasms_c00_c97")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess malignant_neoplasms_c00_c97") +
  theme_minimal()

kable(mar_summary)
```



## nephritis_nephrotic_syndrome

```{r nephritis_nephrotic_syndrome, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="nephritis_nephrotic_syndrome")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess nephritis_nephrotic_syndrome") +
  theme_minimal()

kable(mar_summary)
```


## other_diseases_of_respiratory

```{r other_diseases_of_respiratory, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="other_diseases_of_respiratory")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
  #filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess other_diseases_of_respiratory") +
  theme_minimal()

kable(mar_summary)
```


## septicemia_a40_a41

```{r septicemia_a40_a41, fig.width=8, fig.height=2.2, warning=F, message=F}
df <- causes %>%
    filter(type=="septicemia_a40_a41")

mar <- df %>% 
  filter(mmwr_year==2020) %>% 
  filter(mmwr_week %in% weeks_march) %>% 
  mutate(excess_is=case_when(
    obs < lpi ~ "Lower than range",
    obs > upi ~ "Higher than range",
    TRUE ~ "Within the range"
  )) %>%
  arrange(desc(unexplained.cases)) %>% 
  rename(deaths=obs,
         `excess deaths`=unexplained.cases,
         expected=pred,
         `expected upper range`=upi,
         `expected lower range`=lpi
  ) 

mar_summary <- mar %>% 
  filter(state %in% states_list) %>% 
  group_by(state) %>% 
  summarize(deaths=sum(deaths),
          `excess deaths`=sum(`excess deaths`))

#mar_states <- mar %>% 
 # filter(excess_is=="Higher than range") %>% 
#  pull(state)

## now for charting
df_chart <-  df %>% 
  filter(mmwr_year==2020) #%>% 
 # filter(state!="US")

df_chart %>% 
  #filter(state %in% mar_counties) %>% 
  filter(mmwr_week %in% weeks_in) %>% 
  filter(state %in% states_list) %>% 
  ggplot(aes(week_end, obs)) +
  geom_ribbon(aes(ymin=lpi, ymax=upi), fill="gray70", alpha=.8) +
  geom_line(color="firebrick", size=.5) +
  facet_wrap(~state, ncol=6, scales="free_y") +
  labs(title="State excess septicemia_a40_a41") +
  theme_minimal()

kable(mar_summary)
```